from .featureplot import Featureplot
from .modified_cell_type import Modified_cell_type
from .diff import Diff
from .sub_clusters import Sub_Clusters
from .sub_clusters_old import Sub_Clusters_old
from .singleR import SingleR
from .enrichment import Enrichment
from .scenic import Scenic
from. decontX import DecontX
from .monocle2 import Monocle2
from .addmodulescore import Addmodulescore
