# 物种信息配置文件
# 新增可直接复制该模板
# species:
#   anno: 
#   KEGG:
#   GO_BP:
#   Hallmakr: 
#   singleR:
#     default:
#     others:

# 人 默认
human:
  anno: /data/database/cellranger-refdata/refdata-gex-GRCh38-2020-A/ 
  KEGG: /data/database/GSEA_gmt/human/v2023/c2.cp.kegg.v2023.1.Hs.symbols.gmt
  GO_BP: /data/database/GSEA_gmt/human/v2023/c5.go.bp.v2023.1.Hs.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/h.all.v2023.1.Hs.symbols.gmt
  scenic: /data/database/SCENIC/human
  singleR:
    default: /data/database/celltype_refdata/Human/logNorm_rds/hpca.rds
    pbmc: /data/database/celltype_refdata/logNorm_rds/blueprint_encode.rds


# 人 2020
human_2020:
  anno: /data/database/cellranger-refdata/refdata-gex-GRCh38-2020-A/ 
  KEGG: /data/database/GSEA_gmt/human/v2023/c2.cp.kegg.v2023.1.Hs.symbols.gmt
  GO_BP: /data/database/GSEA_gmt/human/v2023/c5.go.bp.v2023.1.Hs.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/h.all.v2023.1.Hs.symbols.gmt
  scenic: /data/database/SCENIC/human
  singleR:
    default: /data/database/celltype_refdata/Human/logNorm_rds/hpca.rds
    pbmc: /data/database/celltype_refdata/logNorm_rds/blueprint_encode.rds

# 人 2024
human_2024:
  anno: /data/database/cellranger-refdata/refdata-gex-GRCh38-2024-A/
  KEGG: /data/database/GSEA_gmt/human/v2023/c2.cp.kegg.v2023.1.Hs.symbols.gmt
  GO_BP: /data/database/GSEA_gmt/human/v2023/c5.go.bp.v2023.1.Hs.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/h.all.v2023.1.Hs.symbols.gmt
  scenic: /data/database/SCENIC/human
  singleR:
    default: /data/database/celltype_refdata/Human/logNorm_rds/hpca.rds
    pbmc: /data/database/celltype_refdata/logNorm_rds/blueprint_encode.rds

# 小鼠  默认 2020
mouse:
  anno: /data/database/cellranger-refdata/refdata-gex-mm10-2020-A/
  KEGG: /data/database/GSEA_gmt/mouse/v2024/gene_kegg.gmt
  GO_BP: /data/database/GSEA_gmt/mouse/v2023/m5.go.bp.v2023.1.Mm.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/mh.all.v2023.1.Mm.symbols.gmt
  scenic: /data/database/SCENIC/mouse
  singleR:
    default: /data/database/celltype_refdata/Mouse/logNorm_rds/immgen.rds
# 小鼠 2020
mouse_2020:
  anno: /data/database/cellranger-refdata/refdata-gex-mm10-2020-A/
  KEGG: /data/database/GSEA_gmt/mouse/gene_kegg.gmt
  GO_BP: /data/database/GSEA_gmt/mouse/v2023/m5.go.bp.v2023.1.Mm.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/mh.all.v2023.1.Mm.symbols.gmt
  scenic: /data/database/SCENIC/mouse
  singleR:
    default: /data/database/celltype_refdata/Mouse/logNorm_rds/immgen.rds

# 小鼠 2024
mouse_2024:
  anno: /data/database/cellranger-refdata/refdata-gex-GRCm39-2024-A/
  KEGG: /data/database/GSEA_gmt/mouse/gene_kegg.gmt
  GO_BP: /data/database/GSEA_gmt/mouse/v2023/m5.go.bp.v2023.1.Mm.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/mh.all.v2023.1.Mm.symbols.gmt
  scenic: /data/database/SCENIC/mouse
  singleR:
    default: /data/database/celltype_refdata/Mouse/logNorm_rds/immgen.rds

# 大鼠
rat:
  anno: "/data/database/cellranger-refdata/refdata-mRatBN7/"
  KEGG: "/data/database/GSEA_gmt/rat/gene_kegg.gmt"
  GO_BP: /data/database/GSEA_gmt/rat/gene_go_bp.backgroud.gmt
  Hallmakr: "unknown"
  singleR:
    default: /data/database/celltype_refdata/Mouse/logNorm_rds/immgen.rds
# 大鼠 新版
rat_new:
  anno: "/data/database/cellranger-refdata/refdata-mRatBN7_new/"
  KEGG: "/data/database/GSEA_gmt/rat/gene_kegg.gmt"
  GO_BP: /data/database/GSEA_gmt/rat/gene_go_bp.backgroud.gmt
  Hallmakr: "unknown"
  singleR:
    default: /data/database/celltype_refdata/Mouse/logNorm_rds/immgen.rds
# 大鼠 v6
rat_v6:
  anno: "/data/database/cellranger-refdata/refdata-cellranger-Rnor_6.0/"
  KEGG: "/data/database/GSEA_gmt/rat/gene_kegg.gmt"
  GO_BP: /data/database/GSEA_gmt/rat/gene_go_bp.backgroud.gmt
  Hallmakr: "unknown"
  singleR:
    default: /data/database/celltype_refdata/Mouse/logNorm_rds/immgen.rds

sheep:
  anno: "/data/database/cellranger-refdata/refdata-ARS-UI_Ramb_v2.0/"
  KEGG: /gpfs/oe-scrna/further_analysis/scRNA/10x/DZOE2023081524/Ovis_aries/kegg.gmt
  GO_BP: /gpfs/oe-scrna/further_analysis/scRNA/10x/DZOE2023081524/Ovis_aries/go.gmt
  Hallmakr: "unknown"

sheep2:
  anno: "/gpfs/oe-database/cellranger-refdata/refdata-Oar_v4.0/"
  KEGG: "unknown"
  GO_BP: "unknown"
  Hallmakr: "unknown" 
  

# 香港斑马鱼
zebrafish_HK:
  anno: /gpfs/oe-scrna/further_analysis/scRNA/10x/DZOE20230779114/20240517-20240524/ref/Drerio_genome/
  GO_BP: /gpfs/oe-scrna/zhaoyouwei/houxu/DZOE20230779114-Danio_rerio/1129_2/gs_merge.gmt
  scenic: /data/database/SCENIC/human
  singleR:
    default: /gpfs/oe-database/celltype_refdata/logNorm_rds/hpca.rds
    pbmc: /data/database/celltype_refdata/logNorm_rds/blueprint_encode.rds

#猪
pig:
   anno: /data/database/cellranger-refdata/refdata-Sus_scrofa/
# 牛
cow:
  anno: /gpfs/oe-database/cellranger-refdata/refdata-Bos_taurus_old/

#小鼠 mobivision
mouse_mobi: 
  anno: /data/database/mobivision-refdata/mobivision-mm10-2020-A/


#乌头
wutou:
  anno: /data/database/mobivision-refdata/wuto_gencode_v3/

#山葡萄
shanputao:
  anno: /gpfs/oe-scrna/lishuai/genome_prepare/shanputao/Vitis_amurensis/

#绵羊
sheep_v4:
  anno: /gpfs/oe-scrna/genome_reference/Mobi/refdata-Oar_v4.0/refdata-Oar_v4.0

# 鸡
Gallus_gallus:
  anno: /gpfs/oe-database/cellranger-refdata/refdata-Gallus_gallus/ensembl_release-106

#goat 山羊
goat:
  anno: /gpfs/oe-database/cellranger-refdata/refdata-cellranger-Capra_hircus/NCBI/